### ISSUE TITLE
Subresource integrity

### ISSUE THREAD

**Issue by ruricolist** [filamentgroup/loadCSS#106]
It would be nice if you could specify a value for the `integrity` attribute of the link, to enforce [subresource integrity](http://www.w3.org/TR/SRI/).

**Comment by scottjehl** [comment]
Nice idea. +1

**Comment by zachleat** [comment]
Ooh yes I like this.

**Comment by XhmikosR** [comment]
I've opened #204 the other day without noticing this issue. I guess it's the same issue after all.

**Comment by scottjehl** [comment]
As mentioned in #204, I'm not sure how this would work if the attribute is only allowed with `link[rel=stylesheet]`. We could polyfill it but that wouldn't help native support.

**Comment by XhmikosR** [comment]
@sideshowbarker : @scottjehl is right. If we use `rel="stylesheet preload"` this would not work in Chrome, would it?

**Comment by sideshowbarker** [comment]
> If we use `rel="stylesheet preload"` this would not work in Chrome, would it?

Why would it not work? Neither the Preload spec nor the HTML spec prohibits it.

Or am I misunderstanding something?

What I do know is that the HTML spec defines the value of the `rel` attribute as [a set of space-separated tokens](https://html.spec.whatwg.org/multipage/semantics.html#attr-link-rel) and the HTML spec requires it to be parsed that way and for UAs to process it based on what the value _contains_, not on an exact match against the entire value.

**Comment by sideshowbarker** [comment]
> As mentioned in #204, I'm not sure how this would work if the attribute is only allowed with `link[rel=stylesheet]`.

Per https://html.spec.whatwg.org/multipage/semantics.html#attr-link-integrity it’s allowed if the `rel` value _contains_ `stylesheet` (not just _is_ `stylesheet`). Since the `rel` attribute can contain a set of values, it can contain both `stylesheet` and `preload` and still conform to that requirement.

**Comment by sideshowbarker** [comment]
My previous comments were mostly just about the context document-conformance requirements. I guess https://github.com/w3c/webappsec-subresource-integrity/issues/26 is more relevant as far as the UA requirements.

**Comment by XhmikosR** [comment]
@scottjehl: in theory if we changed the check in preload to `link.rel.indexOf("preload") !== -1` should work.

Can you verify?

**Comment by scottjehl** [comment]
I'm not sure that specifying both values would behave as one would want... would it block or fetch async? I've not seen this spec'd or tested.

**Comment by XhmikosR** [comment]
Please wait a few minutes so that @sideshowbarker explains the situation as discussed on IRC.

**Comment by sideshowbarker** [comment]
> I'm not sure that specifying both values would behave as one would want... would it block or fetch async? I've not seen this spec'd or tested.

Yeah, see related discussion at http://logs.glob.uno/?c=freenode%23whatwg&s=14%20Feb%202017&e=14%20Feb%202017#c1020544 among @yoavweiss and @zcorpan and @annevk

**Comment by scottjehl** [comment]
So @sideshowbarker it seems that folks want to allow SRI to work with `preload` alone, but it currently does not, and specifying `rel="stylesheet preload"` will currently block rendering. Is that correct? If so, should we wait on this one? We can polyfill it but we'd want native support to work as expected first...

**Comment by zcorpan** [comment]
Waiting for this to be figured out in browser implementation first seems very reasonable to me. Meanwhile you can use `rel="preload" data-integrity="..."` and add the `integrity` attribute at the same time as adding the `stylesheet` relation.

**Comment by zcorpan** [comment]
(I don't know if there was an issue in reusing a sans integrity preloaded resource as an integrity stylesheet... @yoavweiss?)

**Comment by XhmikosR** [comment]
>Waiting for this to be figured out in browser implementation first seems very reasonable to me. Meanwhile you can use rel="preload" data-integrity="..." and add the integrity attribute at the same time as adding the stylesheet relation.

That is a cleaver workaround! Have you tried it in action?

**Comment by yoavweiss** [comment]
> (I don't know if there was an issue in reusing a sans integrity preloaded resource as an integrity stylesheet... @yoavweiss?)

I wouldn't expect that to work

**Comment by scottjehl** [comment]
This is supported now in 2.1.0! See the attributes argument if you want to use it. Thanks!

**Comment by comp500** [comment]
Does this work with just the rel=preload polyfill, or is manual loading with loadCSS required?

**Comment by scottjehl** [comment]
@comp500 good question. I'd need to test it before answering that. If that attribute works with `rel=preload` in general, then I'd expect it to work alright with this. If you get to test it before I get to it, we would love to know what you find. Thanks.

**Comment by comp500** [comment]
I've tested the integrity attribute using the rel=preload polyfill, using the following code:
```html
<link rel="preload" href="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.css" integrity="sha384-dbVIfZGuN1Yq7/1Ocstc1lUEm+AT+/rCkibIcC/OmWo5f0EA48Vf8CytHzGrSwbQ" crossorigin="anonymous" as="style" onload="this.onload=null;this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.css" integrity="sha384-dbVIfZGuN1Yq7/1Ocstc1lUEm+AT+/rCkibIcC/OmWo5f0EA48Vf8CytHzGrSwbQ" crossorigin="anonymous"></noscript>
<script>
/*! loadCSS. [c]2017 Filament Group, Inc. MIT License */
// [loadCSS source here]
</script>
```
In both Chrome and Firefox, the site does load KaTeX properly, so the loadCSS polyfill and `this.rel='stylesheet'` do work to some extent.

In Chrome, which supports rel=preload natively, the following errors are printed in the log:
```
A preload for 'https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.css' is found, but is not used due to an integrity mismatch.
The resource https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/katex.min.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```
If I change the integrity attribute such that SRI is violated, Chrome will still preload the css file, then display the errors above and also refuse to load the actual stylesheet due to the SRI violation. This is probably because it ignores the integrity attribute when rel=preload is used.

In Firefox, no errors about SRI are printed when the integrity attribute is correct, even when `network.preload` is enabled in the config. Therefore, the rel=preload polyfill itself seems to work correctly with SRI, as the integrity attribute is applied to the stylesheet when the script loads.

There do seem to be a few issues on Chromium's issue tracker and two w3c issue trackers: [chromium #677022](https://bugs.chromium.org/p/chromium/issues/detail?id=677022), https://github.com/w3c/preload/issues/127 and https://github.com/w3c/webappsec-subresource-integrity/issues/26.
Until those issues are solved, it may required to use manual loading, or just the polyfill (without `this.rel='stylesheet'`), as the official rel=preload specification doesn't seem to account for SRI.
