### ISSUE TITLE
Link insertion with preload

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [filamentgroup/loadCSS#129]
Dear @scottjehl ,

Your code [here](https://github.com/filamentgroup/loadCSS/blob/master/src/cssrelpreload.js#L22) in the file cssrelpreload.js has an automatic 'before' argument which is link. 

`w.loadCSS( link.href, link );`

This isn't ideal, isn't it? Because, since it's preload, people will put the `<link rel="preload"` as much early in the head as possible and before inline/critical styles. So the link will get inserted before inline styles.

**Comment by scottjehl** [comment]
@vijayaraghavanramanan that's a good question. I was trying to make the polyfill line up with how it'd behave in a supported environment, so that's why it injects in-place. For example, in Chrome Canary, this script won't do anything because the link rel=preload feature is supported. So in that browser the stylesheet will load using the same link tag. 

I think the best approach may be to place your link after your inline styles, even if that means the fetch leaves later than it would during preparse. I'm guessing it won't make too big of a difference but I can't say.

Closing out as wontfix but happy to reopen and discuss further. Thanks!

**Comment by vijayaraghavanramanan** [comment]
Hi Scott, 

Yeah that makes sense. Agree fetch leaving later won't make much difference. 

There's one more thing. I hope it's okay for me to ask here and not open another issue. 

I have observed that on second load, IE8 and below paint using the styles within @media print {...} rules. I modified your code at my end and blocked render by checking for media query feature detection. i,e, I use a condition like 

`var matchMedia = window.matchMedia || window.msMatchMedia;
    if (matchMedia) { ...`

and then set media to `media || "all"` and immediately inject the sheets if the condition is false.  

When I do that, IE8 and below work fine. 

So I guess older browsers might need to be explicitly render blocking in loadCSS? (ie by not setting media to "only x")?
