### ISSUE TITLE
Order of Link and Scripts Matters in Firefox - needs retesting

### ISSUE THREAD

**Issue by StevenFlecha** [filamentgroup/loadCSS#172]
The support table in the readme is nonsense..
it does NOT work on latest version of FF (46.0.1) and neither in IE (11.0)

**Comment by scottjehl** [comment]
@StevenFlecha can you post an example? That'd represent a big change in those releases if that's true, but we do test this regularly and latest FF and IE were covered at release time. Thanks.

**Comment by fatjester** [comment]
I noticed in the newest Firefox and Edge that if the <link rel="preload"... is coded after the <script... block (instead of before as it is in the test/preload.html example), then the polyfill does not work.

I can't verify that it worked on earlier versions, but even though this ordering of tags might not be optimal, it is acceptable and it would be better if the polyfill worked regardless of order.

That said, still amazing and thanks for making it :)

**Comment by StevenFlecha** [comment]
sorry, I already completely removed it.. I did put it rather hastily to test out so maybe I did something wrong.. when I have some more time to test I'll report. But result was that css was just completely not loading (and it did on chrome)

**Comment by wifiextender** [comment]
`head`

```javascript
<script>
      (function() {
      'use strict';
      var head = document.getElementsByTagName('head')[0];
      var bootnap = document.createElement('link');
      bootnap.rel = 'stylesheet';
      bootnap.href = './css/bootstrap-theme1.min.css';
      head.appendChild(bootnap);
      }());
</script>
```

Before `</body>`

```html
<link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
```
Result:

![1](https://cloud.githubusercontent.com/assets/4725121/15572600/da1a7fb2-2341-11e6-952c-8ffbc21cbbb9.png)

---

`head`

```javascript
<script>
// notice the difference between this one and the first one
      (function() {
          'use strict';
          var head = document.getElementsByTagName('script')[0];
          var bootnap = document.createElement('link');
          bootnap.rel = 'stylesheet';
          bootnap.href = './css/bootstrap-theme1.min.css';
          bootnap.media = 'only x';
          head.parentNode.insertBefore(bootnap, head);
          setTimeout(function() {
            bootnap.media = 'all';
          });
      }());
</script
```
Before `</body>`

```html
<link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
```

Result:

![2](https://cloud.githubusercontent.com/assets/4725121/15572601/da389ce0-2341-11e6-9a29-d444c0017689.png)

---

In the `head`

```javascript
<script>
      (function() {
          'use strict';
          var head = document.getElementsByTagName('script')[0];
          var bootnap = document.createElement('link');
          bootnap.rel = 'stylesheet';
          bootnap.href = './css/bootstrap-theme1.min.css';
          bootnap.media = 'only x';
          head.parentNode.insertBefore(bootnap, head);
          setTimeout(function() {
            bootnap.media = 'all';
          });
      }());
</script>
```

Before `</body>`
```javascript
<script>
          var xhr = new XMLHttpRequest();
          xhr.timeout = 4000;
          xhr.overrideMimeType('text/css; charset=UTF-8');
          xhr.onreadystatechange = function() {
              if (xhr.readyState === 4 && xhr.status === 200) {
                  var style = document.createElement('style'),
                      lastJS = document.getElementsByTagName('script')[2];
                  style.appendChild(document.createTextNode(xhr.responseText));
                  lastJS.appendChild(style);
              }
          };
          xhr.open('GET', 'https://fonts.googleapis.com/css?family=Roboto:400,700', true);
          xhr.send(null);
</script>
```

Result:

![3](https://cloud.githubusercontent.com/assets/4725121/15572602/da59b498-2341-11e6-8b7c-e113fe2da6a7.png)

**Comment by neuropass** [comment]
Yes you need 3 scripts so the polyfil can run, see here: 
https://github.com/filamentgroup/loadCSS/issues/177

if someone can update the readme file that would be great. not sure hwo it was missed in the first place.

**Comment by kwoxer** [comment]
I have the same issue. I'm using Firefox on Ubuntu. Both are latest.

Also I'm using Firefox and also Firefox Dev. I have the same issue in both browser.

This is what my `html.tpl` looks like:
```
<script>
    /*! loadCSS: ... */
...
    /*! preoadCSS: ... */
...
  </script>
  <link rel="preload" href="/sites/all/themes/learnattack/css/main.css" as="style" onload="this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="/sites/all/themes/learnattack/css/main.css"></noscript>
  <style>
```
this works great in **Chrome**. It is loading the main.css via lazy loading. And also after a reload the `main.css` is still cached.

This issue is with **Firefox**/Dev. Here the main.css is somehow loaded 2 times but with a different size (unzipped). Here is a pic: http://i.imgur.com/7MDcpAM.png

So why is Firefox not loading the `main.css` from the Cache after the first visit? And why Firefox is loading the main.css 2 times?

This makes no sense for me because in Chrome it works perfectly well!

Thanks for any idea.

**Comment by fatjester** [comment]
This main example is working for me in in both Firefox, and Firefox dev - there is an intentional 5 second delay to show that it doesn't block rendering while waiting.  You might be having a different issue than the other people in the thread.

**Comment by kwoxer** [comment]
Sure, sure. It works in Firefox. And main.css is loaded 5 sec later.

But! If you reload the page it happens again and again and again! This shouldn't! 

And yes in all other browser, this is working. Even in Internet Explorer!

Could you recheck this on your Firefox? Thank you.

**Comment by fatjester** [comment]
I refreshed example you listed several times with both FF, and FF dev and each time the css loads about 5 seconds later.  However, main.css isn't a stylesheet in the example, it should be "slow.php".

If you are having an issue with your implementation as you described it above - with your css called after the script, then you might be having the same issue discussed in the thread, but that issue doesn't affect the http://filamentgroup.github.io/loadCSS/test/preload.html example because it's css is called before the script.

There was an pull request from a while back committed yesterday that addresses the firefox issues, so if you are testing your own site, you may want to try the updated code.

**Comment by kwoxer** [comment]
Somehow it seems that Firefox is kind of strange. Sometimes it behaves as expected, but often it reloads the main.css. It also has to be simething with an open toolbox. Although I didn't check the checkbox to disable Cache. Very sad, that this just happens in Firefox. :(

Hard to find this issue for that. But I think it's a bug in Firefox. Maybe I should post it as Firefox issue? WDYT?

**Comment by scottjehl** [comment]
Thanks. Chiming in now a bit late.

so, it's expected that behavior will vary in Firefox and Chrome. The script will in fact do nothing in Chrome because rel=preload is natively supported there. In non-supported browsers like Firefox, you'll get the polyfill behavior. Support is still not wide: http://caniuse.com/#feat=link-rel-preload

As for the order of the markup, that situation may now be less particular as of a commit that landed on Dec 19 that should ensure the polyfill is called with one late check. https://github.com/filamentgroup/loadCSS/commit/c04222b888f49127eaf7c437926d5689de1fe785

That said, we do recommend listing the link first, then the script that polyfills it. I'll test this on Monday a bit more thoroughly, but if anyone has time to test the order of the markup both ways, that'd be really helpful. We'll want to test a few common browsers that do not support link rel preload.

**Comment by scottjehl** [comment]
updated the title of issue...

**Comment by scottjehl** [comment]
Does not seem to matter anymore. Switched order demo for testing purposes: https://master-origin-loadcss.fgview.com/test/preload-switch.html
