### ISSUE TITLE
When to use cssrelpreload.js and onloadcss.js?

### ISSUE THREAD

**Issue by dep** [filamentgroup/loadCSS#185]
The documentation is a bit sparse here as far as when to use the two other .js files within the src/ tree.  cssrelpreload.js and onloadcss.js.

Should we always be including these? If so in what order?

**Comment by johanson** [comment]
Check out the [https://github.com/filamentgroup/loadCSS#recommended-usage-pattern](https://github.com/filamentgroup/loadCSS#recommended-usage-pattern). This is probably the way to do it.

The documentation really is a bit sparse and difficult to understand at first.

From my understanding and the way it works for me: 

- First the CSS file(s) you want to load `<link rel="preload" href="file.css">`
- Then CSSrelpreload.js and after that loadCSS.js. Both inline to not make blocking, additional requests and minified.

CSS file needs to be before because calling CSSrelpreload and loadCSS, since there are some reported bugs if it is the other way around and it doesn't look like it has been fixed yet.

**Comment by dep** [comment]
Thank you for the info. :)

**Comment by scottjehl** [comment]
Thanks for the nudge. I think the docs need to be cleaned up to clarify that loadCSS is primarily recommended now as a polyfill for `rel=preload`. You can bundle it and call the function manually when needed of course, but we think that's going to be more of a secondary use case now.

**Comment by fabioformosa** [comment]
I get a warning of blocking resources by Google Page Insight if I put polyfill CSSrelpreload.js after loadCSS.js like [loadCSS demo](http://filamentgroup.github.io/loadCSS/test/preload.html)  shows.
@johanson I agree with about the right order. I recap: 

1.  CSS link with rel="preload"

1.  js inline script: **first** polyfill  CSSrelpreload.js and **after** loadCSS.js (both minified)

@scottjehl I'd ask you to confirm me if my reported order of CSSrelpreload/loadCSSs inclusion is right also if it's inverted than loadCSS demo.

**Comment by liltinkerer** [comment]
It doesn't matter what Google's pagespeed think or says, use your console to check if everything works and indeed is async.

**Comment by fabioformosa** [comment]
If everything works it's enough if you run webapps in localhost, otherwise let me say,  what Google thinks or says it's as holy as holy bible.

**Comment by scottjehl** [comment]
The recommended use pattern is called out first thing in the readme, so I think it's clear enough to close out this issue. We'll try and improve the wording though, thanks for that. As for the pagespeed part, I noted in the specific issue from @fabioformosa that PSI's had trouble with this blocking recommendation for a while. We'd recommend testing and verifying with webpagetest and devtools if it gives you this warning. Thanks!
