### ISSUE TITLE
Seeing duplicated rules in my Chrome/FF development tools

### ISSUE THREAD

**Issue by dep** [filamentgroup/loadCSS#187]
Hello!  When I inspect an element on my page in Chrome or Firefox, I'm seeing the same CSS applied twice, even though the Network inspector only shows the CSS file being loaded once.

Screenshot: http://dl.dpeck.net/Or9F

I'm not doing anything off-pattern when I include the CSS along with loadCSS as the polyfill: http://dl.dpeck.net/sP4N

Any help appreciated. Thanks!

**Comment by rsteinwand** [comment]
Is this the issue you're seeing: https://github.com/filamentgroup/loadCSS/issues/110

**Comment by dep** [comment]
Thanks for the reply. I saw that thread as well. I don't think so, as I think that thread was more related to two separate network requests happening for the same file. For this, there's only one network request.

**Comment by ivnmaksimovic** [comment]
@dep Are the rules coming from the same file? Maybe the first set of rules is from critical css that you are inlining? Just a guess.

**Comment by MarcoHengstenberg** [comment]
I had this issue as well. What solved it for me is the following pattern of loading stylesheets:

```
<head>
    <link rel="preload" onload="this.rel'stylesheet'"  as="style" href="foo.css" />
    <noscript><link rel="stylesheet" href="foo.css" /></noscript>
</head>
<body>
    …
    <script>
    /* loadCSS script */
    /* preloadPolyfill script */
    </script>
</body>
```

What's important is to dismiss the extra call via `loadCSS('.foo.css');` because that adds a second instance of the `<link rel="stylesheet" href="foo.css" />` to the DOM on top of the one in the <head> where on the onload event the rel attribute of `preload` will be switched out against `stylesheet`.

So, when only using loadCSS you need the call `loadCSS('foo.css');` but with the poly fill that's superflous.

**Comment by scottjehl** [comment]
@MarcoHengstenberg covered this well. The polyfill will call loadCSS for you (if preload isn't supported natively) by simply including the script. So, no need to call loadCSS() yourself. Thanks
