### ISSUE TITLE
Pagespeed Insights (again)

### ISSUE THREAD

**Issue by rsteinwand** [filamentgroup/loadCSS#193]
https://groups.google.com/forum/#!topic/pagespeed-insights-discuss/cLjjfeqEtfQ

I think Josh Marantz is part of the Mod Pagespeed team.

> I am not fully convinced that LoadCSS implements the delay-loading heuristics suggested in https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery.

>In particular I scanned https://github.com/filamentgroup/loadCSS/blob/master/src/loadCSS.js and did not see a reference to 'requestAnimationFrame' which in my opinion is required to ensure that the browser renders the content without waiting for the CSS.  You can argue that it should be necessary, that a combination of setTimeout & onload should be sufficient, but we did not find that to be sufficient when we were tuning the mod_pagespeed prioritize_critical_css implementation.

>The other question is whether you have really inlined your critical CSS.  Even if LoadCSS does properly delay-load the main CSS, if it turns out that it is required for displaying the page, then PSI will ding you for this.

>-Josh

**Comment by zwacky** [comment]
I also implemented the loadCSS approach, but the pagespeed reporting (https://testmysite.withgoogle.com/intl/de-de) still said, I had blocking CSS.

You mentioned requestAnimationFrame, which was used in this approach that I used, and was successful with it:

```
<script>
        var cb = function() {
            var l = document.createElement('link'); l.rel = 'stylesheet';
            l.href = 'https://static.justwatch.com/static/compile_jw/assets/jw-webapp-0.11.112.css';
            var h = document.getElementsByTagName('head')[0]; h.parentNode.insertBefore(l, h);
        };
        var raf = requestAnimationFrame || mozRequestAnimationFrame || webkitRequestAnimationFrame || msRequestAnimationFrame;
        if (raf) {
            raf(cb);
        } else {
            window.addEventListener('load', cb);
        }
    </script>
```

**Comment by scottjehl** [comment]
Hi folks. RAF is a fine way to do it too. Google folks tend to recommend loadCSS's approach often as well, and it's async too. The way it works is the link is inserted immediately but its media type is set to a value that will not match, which triggers the browser to fetch at a low-priority, async manner, and once it loads the media is set to an applicable type (`all` or any custom value). This is the same behavior as how `print` media links are fetched. 

It's true that Pagespeed Insights has had trouble identifying loadCSS as async in some implementations. In the past, the team flagged this as a PSI bug, but you can verify that it does indeed request asynchronously when tested.

I'd say the advantages with the plain loadCSS() method over RAF are 1) loadCSS starts loading immediately, as opposed to after the first frame renders, and 2) broader compatibility (loadCSS is reliable in older non-RAF browsers). 

All that said, now that standards have caught up, I'd recommend using loadCSS purely as a polyfill for  the new `link[rel=preload]` instead of calling it loadCSS manually. I'll be restructuring the Readme to make this clearer but it's in there now as the primary recommended workflow: https://github.com/filamentgroup/loadCSS#recommended-usage-pattern

The linked demo in that section includes the pattern as recommended.

**Comment by shrpne** [comment]
@scottjehl 
> It's true that Pagespeed Insights has had trouble identifying loadCSS as async in some implementations. In the past, the team flagged this as a PSI bug, but you can verify that it does indeed request asynchronously when tested.

Looks like Pagespeed still have this problem. Could you specify link to the issue please. And may be loadCSS can introduce some workaround to it?

**Comment by liltinkerer** [comment]
@shrpne why would loadCSS need to have to workaround for a speed test? If it does load async for browser clients the everything is fine.

**Comment by shrpne** [comment]
@liltinkerer as I know, pagespeed result affects Google search position
