### ISSUE TITLE
Why is the `media` attribute not set to it's final state when using `loadCSS`?

### ISSUE THREAD

**Issue by t-kelly** [filamentgroup/loadCSS#215]
I noticed that the change in `media` from [`only x`](https://github.com/filamentgroup/loadCSS/blob/master/src/loadCSS.js#L26) to [whatever you set or `all`](https://github.com/filamentgroup/loadCSS/blob/master/src/loadCSS.js#L61) was causing a double request in both Chrome and Safari on iOS similar to what is discussed in https://github.com/filamentgroup/loadCSS/issues/110. I believe this is due to my cache headers, but it no longer occurs if I remove the switch.

Why is this switch needed if the `<link>` tag is added with `loadCSS`? Is it still render blocking?

**Comment by scottjehl** [comment]
Hi @t-kelly. Good question. Yes, that is the way that we ensure that the media query does not match when the request is made, which makes the browser request it at a low, and asynchronous, priority. Recently, browsers have been working to improve this behavior and it has always varied. I believe this toggle is still needed for webkit/safari to request without blocking render, but we're always open to suggestions. 

Since you mentioned Chrome though, I should note that we now recommend using loadCSS primarily as a polyfill for `link[rel=preload]`, which chrome natively supports. If you're using this markup pattern, which is recommended first thing in the readme, loadCSS won't actually run at all in Chrome, because it'll detect the preload feature and exit. So, if you're running that markup pattern and see 2 requests in chrome, that is probably a rel=preload bug in chrome.

I'll close this out but if you happen to find that the media toggle is not needed across modern versions of each major browser, we'd look into whether we want to deprecate it.

**Comment by t-kelly** [comment]
Thanks for the confirmation, Scott!
