### ISSUE TITLE
Possible memory leak when used with the same URL multiple times

### ISSUE THREAD

**Issue by lencioni** [filamentgroup/loadCSS#236]
At Airbnb, we are using this package to async load some stylesheets. We are also doing some single-page app stuff. When these two things cross paths, and you end up visiting the same page that calls loadCSS with the same URL multiple times via client-side routing, we believe we end up with a memory leak.

Would you be open to changing this package to avoid adding any given stylesheet to the page more than once? One possible solution would be to use a helper function such as:

```js
function hasStyleSheet(url) {
  var ss = document.styleSheets;
  for (var i = 0; i < ss.length; i++) {
    if (ss[i].href === url) { return true; }
  }
  return false;
}
```

cc @jvilk @adamrneary @thaingnguyen

**Comment by jvilk** [comment]
@lencioni See discussion in PR. You may need to fix this issue in your code that uses loadCSS.

**Comment by scottjehl** [comment]
It's an interesting issue. But I'm not sure if the fix should be in loadCSS or in Airbnb's code. It seems like this same problem could happen similarly without loadCSS, if say, your app was appending the same stylesheet `link` element via its clientside routing instead of calling loadCSS. 

Given the seemingly unique use case, I'm inclined to think that your app's JS should have a check for the stylesheet URL's presence in the DOM before trying to load it. To avoid the DOM crawl, you might instead do this with some sort of state check, through localstorage, sessionstorage, cookies, etc. 

Does that make sense? If not, I'm happy to reopen and discuss further. Thanks!

**Comment by lencioni** [comment]
Yes, that definitely makes sense. Easy enough for us to guard against.

It would probably be worth adding a note to the readme, and it might be worth adding a dev-only check in here that gives a console warning to help people notice and avoid this issue.
