### ISSUE TITLE
How to correct include loadCss

### ISSUE THREAD

**Issue by Mike667** [filamentgroup/loadCSS#243]
Hi, how to correct include loadCss. Google PI say: Your page has 3 blocking CSS resources. This causes a delay in rendering your page.

But css will loaded after page load. What is wrong?

https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fdev.erive.net%2Feconometrica%2Fpage-solutions.html&tab=desktop

Before body close tag i use loadCss and loadCss polyfill scripts from this example https://master-origin-loadcss.fgview.com/test/preload.html

**Comment by rfgamaral** [comment]
I have a feeling that I'm having a similar issue as I posted here: addyosmani/critical#251.

**Comment by shrpne** [comment]
> Pagespeed Insights has had trouble identifying loadCSS as async in some implementations.

According to https://github.com/filamentgroup/loadCSS/issues/193#issuecomment-257614725

BTW, I'm experiencing same issue and wonder if it can be fixed

**Comment by rsteinwand** [comment]
I don't have this issue but didn't have it with Google's script either.

I inline my critical css in the head, followed by my postloaded style sheet. My external script loads deferred just before the closing head tag.

My CssRelPreload script is with the rest of my inlined scripts just before my closing body tag.

**Comment by JMPerez** [comment]
@Mike667 According to pagespeed there are only 2 blocking CSS.

> Your page has 2 blocking CSS resources. This causes a delay in rendering your page.

Did you update anything?

**Comment by Mike667** [comment]
@JMPerez im return old style

<link rel="stylesheet" href="css/style.css">

because i have issues with JS in old and mobile browsers and styles don't include to page.

Now i paste <link rel="stylesheet" href="css/style.css"> in head or after body and its okay for me. Google page insigns show 90+ bal.

**Comment by Moldjuice** [comment]
Hello everyone,

Following the implementation of loadCss on a website, I notice that the PageSpeed Insights test declares twice my CSS as a blocking resource above the flotation line.

I have two styles sheet loaded in my head.

- An external google-font css
- my style sheet main.min.css

`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

<link rel="preload" href="<?php echo $baseUrlCss ?>/main.min.css" as="style" onload="this.onload=null;this.rel='stylesheet'">

<noscript><link rel="stylesheet" href="<?php echo $baseUrlCss ?>/main.min.css"></noscript>

<script>!function(t){...}</script>

<style>body{background-color:#fff;};</style>
<script></script>`

I simulate a critical css (which I have not set up) within style tag.

PageSpeed Insights returns 3 blocking resources above the float line e (google-font makes sense since I do not include it in my tests) but there are two times my personal style sheet.

Someone would have any idea ?

Regards,

**Comment by scottjehl** [comment]
Hi! Google's PSI tool is improved now and should be better about how it analyzes pages that use loadCSS. Closing this out but feel free to ask further questions
