### ISSUE TITLE
IE11: infinite loading loop

### ISSUE THREAD

**Issue by sithmel** [filamentgroup/loadCSS#262]
Version 2.0.1
In my bundle I added the polyfill:
```js
import 'fg-loadcss/src/cssrelpreload';
```
Here's the html
```html
<link rel="preload" href="mycss.css" as="style" onload="this.rel='stylesheet'">
<script async src="mybundle.js"></script>
```
On IE11 is loading the css in an infinite loop

**Comment by MarcoHengstenberg** [comment]
Had the exact same issue with a project and it ranges from IE10 up to Microsoft Edge 16!

**Comment by scottjehl** [comment]
Thanks. Just so I can narrow this down, is the link transformed into a stylesheet properly, and the script's interval continues to run looking for links in the DOM? 

I'm assuming what's happening here is the onload event is firing before your async script begins running its loop, and because of that, its onload handler will never stop the loop, as it would otherwise do if say, the preload script was inlined.

Sounds like we need a timeout or fallback to stop the loop at a late time in case onload already fired.

**Comment by MarcoHengstenberg** [comment]
We built the project according to the recommended pattern in this repository. The only thing we didn't do is nulling the onload handler.

Apart from that we had the following markup in our head just after the `<title>`:

```
<link rel="preload" as="style" href="stylesheet.css" onload="this.rel='stylesheet'" />
<noscript><link rel="stylesheet" href="stylesheet.css" /></noscript>
<script>/* New Preload Polyfill */</script>
```

The rel value had changed to stylesheet as expected but still IE and Edge kept re-requesting the entire HTML, then the stylesheet, then the webfonts, then the page again and never quit.

**Comment by ensemblebd** [comment]
Very difficult to troubleshoot, as it completely tanks the browser dev tools.  
Getting the breakpoint in the right spot has not been easy... Am having same problem. 

Works fine in chrome/safari.

**Comment by ensemblebd** [comment]
Test case for your experimentation follows....

1. Remove loadCss lib from resources in page
2. Open IE Edge , F12 key
3. Paste into console...
```
var link=0;
var links = window.document.getElementsByTagName( "link" );
for( var i = 0; i < links.length; i++ ){
    link = links[ i ];
    if( link.rel === "preload" && link.getAttribute( "as" ) === "style" && !link.getAttribute( "data-loadcss" ) ){
        break;
    }
}
function enableStylesheet() {
    // infinite loop right here.
    console.log("loaded"); 
    link.media = finalMedia; 
}

var finalMedia = link.media || "all";
link.addEventListener( "load", enableStylesheet);

link.media = "only x";
link.rel = "stylesheet";    // calling this triggers the infinite loop of downloading

setTimeout(function() {
    console.log('forcing loaded');
    enableStylesheet();
},3000);
```
Code is straight from the sources.

**Comment by scottjehl** [comment]
Oh I see. So it seems this is actually an onload handler issue and not just a loop that keeps running (without finding links)?

For what it's worth, did you happen to try the markup we recommend in the readme?

We include a `null` setter in the onload now, for the recommended markup:

```
<link rel="preload" href="path/to/mystylesheet.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="path/to/mystylesheet.css"></noscript>
<script>
/*! loadCSS rel=preload polyfill. [c]2017 Filament Group, Inc. MIT License */
(function(){ ... }());
</script>
```

I suppose we could have the script do that too, but the nice thing here is it nulls the `onload` handler even in browsers that support `rel=preload`, which loadCSS will ignore.

**Comment by ensemblebd** [comment]
Excellent! I'll give that a try, definitely didn't see that in the updated readme

**Comment by scottjehl** [comment]
So this is an idea to test out. 

https://github.com/filamentgroup/loadCSS/commit/918a3318f055002b4bee729840e420e057637c7a

It should effectively do what the comments above suggest, but I'm unsure if the script should manipulate (null out) the link's onload attr or not. I think it's safe because the scripts handler will run after the attribute handler has run. Thoughts welcome.

**Comment by scottjehl** [comment]
Test page for that branch is here https://262-origin-loadcss.fgview.com/test/preload.html

**Comment by scottjehl** [comment]
@sithmel would you be able to confirm for us if the issue goes away by updating your `onload` attribute to include this? `onload="this.onload=null;this.rel='stylesheet'"`

I think that's best since it'll cover supported browsers too, and not just those the polyfill runs in.

Beyond that, we're open to removing the event listener too. Not sure if we need to though... Open to ideas.

**Comment by ensemblebd** [comment]
I can confirm this is a valid solution for Edge and IE11. Likely all others as well.

**Comment by sithmel** [comment]
Sorry for being disappeared for a while. I am not able to reproduce the issue in exactly the same conditions.
I trust @ensemblebd test.
Only one thing: https://github.com/filamentgroup/loadCSS/commit/918a3318f055002b4bee729840e420e057637c7a looks like a sensible safety net. Why not applying it anyway ?

**Comment by thasmo** [comment]
Just for the record, `onload="this.onload=null;this.rel='stylesheet'"` worked for me too although it would be nice if a safety net would be baked in; maybe #267 is actually about it, so we don't need `this.onload=null` at all?

**Comment by ryantoft-gm** [comment]
From my brief testing https://github.com/filamentgroup/loadCSS/commit/918a3318f055002b4bee729840e420e057637c7a appears to also resolve issue #261 - related to older Firefox crashing.

**Comment by pldg** [comment]
I had the same issue.  An infinite loading loop on Internet Explorer and Edge.

The problem was caused by an imported webfont in css.

The solution is to remove the import statment from css ~~`@import url('https://fonts.googleapis.com/css?family=Montserrat');`~~ and use the link tag in html `<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">`.

**Comment by mdavo6** [comment]
Thanks @pldg - Had the same issue. Was driving me nuts!

**Comment by scottjehl** [comment]
Closed. Version 2.1.0 of loadCSS is out with this fix.
