### ISSUE TITLE
Pagespeed Insights new "opportunity"

### ISSUE THREAD

**Issue by futtta** [filamentgroup/loadCSS#279]
The recently released update of Google Pagespeed Insights (which is Lighthouse based) now lists an "opportunity" for loadCSS'ed CSS to defer unused CSS (with "estimated savings" in seconds);

![image](https://user-images.githubusercontent.com/181297/48658172-934cf900-ea3d-11e8-8c02-984b313d6554.png)

I guess in order to make use of that opportunity the loadCSS reliance on "preload" would have to be removed and one would have to rely on a pure JavaScript solution to load the CSS (with `rel="defer"` or something similar) after the onLoad event fired.

* Advantages; less network used before onLoad (and no GPSI "opportunity") 
* Disadvantage; CSS is loaded later, so (assuming "above the fold" CSS was inlined) chance of a visitor scrolling down and seeing unstyled content is bigger

What are other's thoughts on this matter?

**Comment by azhuchkov** [comment]
To be honest I was surprised when I enabled **above-the-fold** feature at **Autoptimize** plugin and then found `link="preload"` at stylesheet declaration. And my question was

> Why preload something that proposed to be deferred?

Looking at [outdated PSI manual](https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery) we see this:

> The critical styles needed to style the above-the-fold content are inlined and applied to the document immediately. The full small.css is loaded after initial painting of the page. Its styles are applied to the page once it finishes loading, without blocking the initial render of the critical content.

But [preload spec](https://w3c.github.io/preload/) states that the main `preload` purpose is not asynchronous loading, but _fetching (usually critical) resources as early as possible_.

Maybe this is not a problem on `HTTP 1.1` when browser can freely establish up to 6 connections, but `HTTP/2` multiplexes all requests into single connection and highly prioritized request of non-critical CSS actually blocks browser from pulling images to complete the first painting. The bigger CSS file, the longer user waits for drawing completion.

So, it's not about useless scoring at PSI - non-critical CSS should be definitely deferred instead of being preloaded.

**Comment by scottjehl** [comment]
Some good thoughts on this, thanks. It's a good point that sometimes, often even, we may not want to preload non-critical CSS, but load it later instead to free up early delivery for other things that are more important. Ultimately, I think it depends on the site and its assets, but it also depends on how you're determining which CSS is deemed critical. We typically inline or push the styles that are necessary to render a reasonable portion of the top of the page, but you won't need to scroll far to see elements that are outside of that rendering window. For that reason, I like to load the full stylesheet at a high priority if possible so it applies early. If there are other assets more critical to your delivery than that full stylesheet, you might choose to take another approach.

It's for this reason that we've kept `loadCSS.js` in the codebase here. You can still choose to call `loadCSS( url )` if you'd rather and the stylesheet will load at a lower priority than preload typically will. You can also call loadCSS at any later time that makes sense to your page, such as after a particular event. Onload for example. 

I'd love if we had a link[async] and link[defer] but until then we at least have options like this. I hope that helps?

**Comment by azhuchkov** [comment]
@scottjehl Since I saw the screenshot with `autoptimize_***.css` at the top, I decided it depends/relates to `loadCSS` somehow. Now I see it doesn't. My fault, sorry.

**Comment by futtta** [comment]
it does; AO uses loadCSS to load the full aggregated CSS in a non-render blocking manner :-)

**Comment by futtta** [comment]
> It's for this reason that we've kept `loadCSS.js` in the codebase here. You can still choose to call `loadCSS( url )` if you'd rather and the stylesheet will load at a lower priority than preload typically will. You can also call loadCSS at any later time that makes sense to your page, such as after a particular event. Onload for example.

Well, ideally loadCSS could be called with a parameter to specify the rel on which to act (as 2nd param, used, the first one is for URL would have to remain for backwards-compatibility), in which case we could have rel="deferredload" and loadCSS acts on that as it does not on rel="preload"?

**Comment by azhuchkov** [comment]
> it does; AO uses loadCSS to load the full aggregated CSS in a non-render blocking manner :-)

Ouch... =)

Isn't there some inconsistency between `rel='preload'`  and `onload='this.rel="stylesheet"'`? Like, I want to fetch this resource before any others, but will use it after everything is loaded.

@futtta Have you tried to just add CSS definition to the bottom of the page like Google PSI manual suggests? Frankly speaking, I do not understand all the JS magic they use. Particularly, I wonder why they use `load` event if browser does not support `requestAnimationFrame` instead of just loading it immediately and how `requestAnimationFrame` helps if browser hasn't loaded the stylesheet yet. Anyways, does this way of loading has significant drawbacks?

**Comment by azhuchkov** [comment]
Sorry, I was wrong about `onload` in my previous message.

**Comment by scottjehl** [comment]
Right - in the case of `onload='this.rel="stylesheet"'` the load is referring to the sheet itself and not the window/page.

**Comment by futtta** [comment]
@azhuchkov not really relevant in this issue, but you can change the "injection point" for the full CSS with this code snippet that hooks into AO's API;

```php
add_filter('autoptimize_filter_css_replacetag','inject_css_in_footer');
function inject_css_in_footer() {
  return array('</body>','before');
}
```

This is very unlikely to make a difference to GPSI though :-)

**Comment by snake-345** [comment]
I'm not sure could it help with your problem or not. But just read this issue https://github.com/GoogleChrome/lighthouse/issues/6588
When I read this I figured out that problem not in css blocking, but problem with excess styles for certain page.

**Comment by pratham2003** [comment]
> I'm not sure could it help with your problem or not. But just read this issue [GoogleChrome/lighthouse#6588](https://github.com/GoogleChrome/lighthouse/issues/6588)
> When I read this I figured out that problem not in css blocking, but problem with excess styles for certain page.

This problem is about excess CSS but a generic solution would not be removing excess (unused) CSS for each page or page-type. Removing excess pages could work in some websites ( where CSS required for all pages are entirely different ) but not the most. e.g. on a normal website CSS that's needed on homepage might not be needed on the product/article page.

Creating single file unique CSS file per page or page-type could make the browser download various CSS files with lots of common data and minor variations. Autoptimize has this issue, the present solution is excluding unique CSS/JS.

Intelligent systems could be built that combine common (across whole website) + unique per page/type CSS files but that's a whole different thing.
