### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by Titanas0** [filamentgroup/loadCSS#28]
Hey,

Great job with this script. This is not an issue with the code. It's more of a tweak. To make your great idea more useful to more people.

Can you provide some more examples for the non so technical people out there? For example how to setup loadCSS for 5 CSS?

I can help with writing the wiki page also.

**Comment by zachleat** [comment]
Hey all? What exactly are you trying to do here? If you want to do multiple `loadCSS` calls you should be able to just list them in order.

```js
loadCSS( "first-stylesheet.css" );
loadCSS( "second-stylesheet.css" );
loadCSS( "third-stylesheet.css" );
```

Of course, because it’s all asynchronous there is no guarantee of the order in which they’ll return and apply, but that’s should be ok.

More importantly, I should also mention that you should probably concatenate your stylesheets so that you don’t have to do multiple loadCSS calls.

**Comment by zachleat** [comment]
Closing. Please reopen if needed!
