### ISSUE TITLE
Is it required to add loadCSS.js inline or via http/2 server-push?

### ISSUE THREAD

**Issue by cagross** [filamentgroup/loadCSS#294]
Hello.  [This documentation page](https://github.com/filamentgroup/loadCSS/) says that the loadCSS.js file should be inlined or linked with http/2 server-push.  Is it required to use either of those methods, or merely suggested?  I ask because my site is a WordPress site, and the standard method of adding a JS file to a page is via [wp_enqueue_script()](https://developer.wordpress.org/reference/functions/wp_enqueue_script/), which is in-turn attached to the `wp_enqueue_script` hook.  Would that be a sufficient method of including loadCSS.js?

Someone I know claims to have done so--added loadCSS.js via wp_enqueue_scripts()--and he hasn't seen any ill effects.  loadCSS seems to function as expected on his WordPress site.

Thanks.

**Comment by scottjehl** [comment]
Good question. It depends on what you're using loadCSS to do. If you want loadCSS to load a CSS file that is pretty important to the initial page rendering, then yeah inlining it or pushing it is best. The reason we recommend inlining or pushing loadCSS is because we want the loadCSS to be available to the browser as soon as it encounters the script tag that references it. Without the server pushing the file along with the HTML response, the browser will need to start a new request to the server to get the script after the HTML arrives. Further, if that script tag is not `async`, it'll stop browser rendering until that script loads, which multiplies the delay before the page can render and be used. That said, if you're only looking to use loadCSS for lesser priority stylesheets that can load later, you could load it asynchronously along with other scripts that your page needs and still use loadCSS whenever it loads. So, inlining or push is mostly for cases where you want to use it very early in page load, and without blocking render. 

I hope that helps. Here's a post that gets into how we use it (or rather, the other loadCSS script that polyfills rel=preload) typically: https://www.filamentgroup.com/lab/async-css.html

**Comment by cagross** [comment]
OK thanks for that clarification.
