### ISSUE TITLE
Content Security Policy support

### ISSUE THREAD

**Issue by remyabel** [filamentgroup/loadCSS#297]
Current there is no way that I know of to allow something like `onload=...` without `unsafe-inline`. The proposed features to address this are either not finalized or not yet implemented in major browsers, see: https://github.com/w3c/webappsec-csp/issues/13. Some browsers like Firefox do not follow the spec and allow hashes for inline attributes (I believe), while Chromium does not. It's suggested in the above issue that scripts should programmatically modify event handlers. However, something like the following:

https://github.com/filamentgroup/loadCSS/blob/59be2248d70c5a9f6d5e7de0e894b5ffe811d857/src/cssrelpreload.js#L42

is not friendly with CSP as it counts as an inline attribute. Is there any workaround for this that does not involve hashing the value? Or can we come up with an alternative that doesn't involve setting the inline attribute?

P.S.: we can hash `null` and add it to our CSP, however, I believe one of the concerns is that this is not really "safe" because it's generic enough to allow an attacker to inject that same code on elements we did not intend.

Clarification: there is no problem with whitelisting the inline code for the global `loadCSS` function. This issue is specifically about inline attributes.

**Comment by rasenplanscher** [comment]
Do you get an error from `link.setAttribute( "onload", null );`?
It should just do nothing in your case, right?

> we can hash `null` and add it to our CSP

If you can do that, why is `onload=...` a problem for you?
Also, what would be the point with `null`?

**Comment by remyabel** [comment]
> Do you get an error from link.setAttribute( "onload", null );?

Correct. The error is "Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”)." and points to line 85 in the script.

> Also, what would be the point with null?

Because the attribute becomes `onload=null`, so you need to hash `null`. Just as you would need to hash any other value that would go there.

**Comment by rasenplanscher** [comment]
Ok, I think, I understand now. And as I see it, this is really nothing that can be changed inside the polyfill to enable the recommended usage with CSP.

The safety issue regarding event-handling attributes is about executing code in an unintended context. I cannot see any adverse effect from executing `null` in *any* context. What could happen is that an intended event-handler gets removed. That, however, won't be prevented by CSP anyway, because, as I understand it, it will only check the respective script when it is to be executed.

If `null` is effectively hashed, `onload=null` becomes valid, so if hashing attribute scripts were available cross-browser, that would be a valid strategy.

The main obstacle, however, is that this capability is not available cross-browser, and there's nothing a script can do, as far as I can tell. Which is as it should be, I think. The implications of a script, even a white-listed one, changing the behaviour of your CSP are very far-reaching, and I do not expect that feature to have a high priority.

Finally: At present, only Chrome/Chromium supports `rel=preload` natively, so that's where the `onload` attribute is actually most important.

**Comment by remyabel** [comment]
> Finally: At present, only Chrome/Chromium supports rel=preload natively, so that's where the onload attribute is actually most important.

You're right, I'm an idiot. I forgot the `onload` workaround is used for browsers that don't support `preload`. Thanks for the detailed response.

**Comment by rasenplanscher** [comment]
Regarding the suggested path of attaching event handler programmatically: at that point, I see no advantage over using the `loadCSS` funtion. Do you? I mean, you're scripting your styles anyway 🤷‍♂️ 

You might want to go with an in-between solution: `<link rel=preload>` in `<head>`, and a corresponding `<link rel=stylesheet>` at the end of `<body>`, with event handlers attached by script.

A discussion of the relative merits seems out of scope here, but I think both strategies are better than trying to force the polyfill together with CSP under the circumstances.

**Comment by remyabel** [comment]
Sorry, I was confusing myself. So:

```
link.setAttribute( "onload", null ); 
```

can be replaced with:

```
link.onload = null;
```

As far as I'm aware, this is functionally equivalent and no hashing is required.

The larger problem is that we cannot currently use `onload="this.onload=null;this.rel='stylesheet'"` with CSP in Chromium until `unsafe-hashed-attributes` or similar is supported in a non-experimental release. There was an [attempt](https://github.com/w3c/webappsec-csp/issues/13#issuecomment-342454140) to attach `onload` programmatically but the user claims the approach has issues. 

So I agree that loadCSS cannot do anything, but I still think replacing `setAttribute` will solve a minor inconvenience.

**Comment by rasenplanscher** [comment]
> There was an [attempt](https://github.com/w3c/webappsec-csp/issues/13#issuecomment-342454140) to attach `onload` programmatically but the user claims the approach has issues.

> if the CSS is already cached, say, it looks like it is possible for the link's onload event to trigger before the handler is attached

Yes, that is a very real obstacle. It is, however, overcome by `onloadCSS` because that polls for the stylesheet in the available sheets instead of listening for the `load` event.



> replacing `setAttribute` will solve a minor inconvenience

> As far as I'm aware, this is functionally equivalent and no hashing is required.

Yes, it is functionally equivalent, because in the end, it's the property that counts, not the attribute.

Just to be sure we're on the same page: `As far as I'm aware` only extends to `this is functionally equivalent`, but you have verified that `no hashing is required` with it?
If so, I'm with you on the replacement.
@scottjehl Do you have any thoughts to the contrary?

**Comment by evromalarkey** [comment]
I had the same issue today when I added CSP to my website. So anything new? Is there any workaroud for this?

**Comment by rasenplanscher** [comment]
@evromalarkey 
Nothing new.

Due to the nature of CSP, there will most likely be no new workaround, ever.

Either browsers support hashing attributes or they don't. If and when they do, this works, otherwise not. It's as simple as that.

Consequently, with CSP, it's probably best to use the `loadCSS` function, or, depending on your situation, this:
> You might want to go with an in-between solution: `<link rel=preload>` in `<head>`, and a corresponding `<link rel=stylesheet>` at the end of `<body>`, with event handlers attached by script.
