### ISSUE TITLE
FOUC on 'No Throttled' condition?

### ISSUE THREAD

**Issue by jasonmevius** [filamentgroup/loadCSS#301]
Hi!  I've been optimizing my portfolio site and am confused about some behavior I'm seeing with loadCSS.  See the following link:

http://jasonmevius.com/index_FOUC.html

I've been organizing my information as follows:

<style>*,::after,::before{box-sizing:border-box }html{font-size:62.5% } .... etc.</style>

<link rel="preload" href="/css/combined-04162019.css" as="style" onload="this.onload=null;this.rel='stylesheet'">

<noscript><link rel="stylesheet" href="/css/combined-04162019.css"></noscript>

<script>!function(t){"use strict";t.loadCSS||(t.loadCSS=function ...</script>
</head>

I'm confused, because I'm seeing variability in the results.  I think the CSS is being deferred as desired, but I see the dreaded FOUC sometimes.  

It's been a little hard for me to debug, because it only seems to be happening at non-throttled speeds.  I observe the behavior during normal operation and when I use Firefox's Inspect Element -> Network with 'Disable cache' and 'No throttling'. 

When I try to debug by seeing where exactly in the loading waterfall that the FOUC kicked off by throttling - it won't duplicate.  Any ideas?

**Comment by rasenplanscher** [comment]
Hi Jason 🙂
Thank you for setting aside a page to investigate the issue, that's really helpful 👍

Regarding your FOUC: I could reproduce it unreliably. What I could see, however, is this: When throttling to GPRS, your main assets load in this order:
+ combined.css
+ jquery.js
+ grouped.js

Without throttling, the order is such:
+ jquery.js
+ grouped.js
+ combined.css

I could even observe `combined.css` getting loaded **after** the document's `load` event.

So, it looks like you trigger the transition from spinner to normal view in `grouped.js` before `combined.css` has finished loading, which will cause a FOUC. This is no bug in loadCSS, which looks to be working fine.

You have several options:
+ make your script aware of your stylesheet's load-completion
+ extent your `<style>` to include the critical styles for `l-wrapper`
+ load the stylesheet synchronously
+ inline all your styles

Seeing as you have a one-pager here, I'd just inline your stylesheets. That way you prevent any FOUC, have one less HTTP request, and can leave out the loadCSS overhead.

Hope this helps 🙂👍

----

By the way: I'd also hide `l-wrapper` in such a way that the page doesn't scroll until `page-loader` is removed. Alternatively, make `page-loader` `position: fixed` instead of `position: absolute`.
