### ISSUE TITLE
Add to cdnjs project

### ISSUE THREAD

**Issue by mikeytown2** [filamentgroup/loadCSS#45]
https://github.com/cdnjs/cdnjs#important---no-more-manual-submissions

**Comment by scottjehl** [comment]
I'd be open to this, but I'm not sure I'm convinced on the value of a CDN for this particular script. It's entire value rests on the JS being "inlined" in the page, rather than requested externally. So in that way, something like Bower or NPM makes good sense to me, but I'm not sure about a CDN.

I'm happy to reopen this if you think it warrants further discussion, or if I missed the point, which is entirely likely :) Thanks
