### ISSUE TITLE
[question] - setting cookie for cached css to block rendering

### ISSUE THREAD

**Issue by noahgrant** [filamentgroup/loadCSS#63]
So I have a test branch with async-loaded css using loadCSS, and everything seems to be working as expected (i'm even loading fonts as @scottjehl suggests [in this article](http://www.filamentgroup.com/lab/font-events.html)).  On first visit, only 'above the fold' css is rendered and the rest is loaded in async.  Great.  However, even when the css file is cached, there's a small blip of time from when the DOM is first rendered to when the cached css file is parsed and selectors are matched.  So if, for example, I scroll to the bottom of the page and the refresh, the browser will keep me at the bottom of the page, and I'll see a blip of unstyled content.

Does that make sense?  What do you do to combat this?  One thing that comes to mind would be setting a cookie as Scott did in that article for the fonts and writing (blocking with .writeIn or something) a <link /> stylesheet element for those who presumably have the file cached.  Another option would be to include the _entire_ page's css inline (this sounds like an awful idea, but I'm actually only loading css async for the homepage, and assuming all other pages will have the css file cached after that, so it wouldn't be the worst thing).

Here's a screenshot of the network timeline, where the first entry is the document and the second is the cached css file, with a gap not only between when the first one ends and the second begins, but we obviously won't actually see the styled DOM until the second one ends.

![screen shot 2015-05-20 at 7 16 14 pm](https://cloud.githubusercontent.com/assets/1355779/7740336/b6ae2e08-ff24-11e4-8da4-1872cb5a9916.png)

Thank you so much for any insight!

**Comment by noahgrant** [comment]
just wanted to ping someone on this.  Anyone have any opinions/solutions or am I thinking about this wrong?  I'm thinking for now I'm going to inline the entire homepage styles to avoid the Flash Of Unstyled Below Fold Content.  Uh...yeah.  FOUBFC.

**Comment by scottjehl** [comment]
Yes. We often do set a cookie when using loadCSS to load our full stylesheet so that future page visits can reference that stylesheet directly. It works great, and in the worst case where someone clears their cache but not their cookies, they'll just load the CSS like most every site on the web, missing out on the rendering performance but probably not causing much trouble beyond that.

So I'd recommend trying that for sure, and we maintain Enhance to combine similar scripts that work towards that goal. Here's an example workflow: https://github.com/filamentgroup/enhance#a-fully-configured-head-setup-for-enhancejs

That said, I don't think it'd be ideal to combine loadCSS with our cookie script so that it could always set a cookie. Sometimes we don't want to set one, and of course cookies bring liabilities in some countries (you have to let the user know when you set them). Anyway, that's how we use it!

**Comment by noahgrant** [comment]
thank you, @scottjehl!
