### ISSUE TITLE
loadCSS code above or below inline?

### ISSUE THREAD

**Issue by superpoincare** [filamentgroup/loadCSS#82]
I understand this code works best for inline and defer. The question is should the inline style go above your javascript or below it?

**Comment by zbeekman** [comment]
Playing around with this I have found that the inline style always takes precedence over the deferred load. Also, I put it after and Google PageSpeed seemed to be satisfied with that. Right now, I can't quite figure out how to automatically extract above the fold critical css *accurately* so using inline and defer loading is not an acceptable solution for me, because the inline css is not accurate, and won't even be corrected when loading the actual css.

**Comment by scottjehl** [comment]
Per the docs, we'd highly recommend placing the loadCSS inline script after your inline CSS `style` element, and specifying its own `script` element via the `before` argument, so that it is injected in a consistent place regardless of your users' extensions and such (which can mess with dom order):

See here for configuring the `after` arg:
https://github.com/filamentgroup/loadCSS#optional-arguments

**Comment by superpoincare** [comment]
Thanks Scott.
